name        : gconf
version     : 3.2.6
release     : 9
source      :
    - http://ftp.gnome.org/pub/gnome/sources/GConf/3.2/GConf-3.2.6.tar.xz : 1912b91803ab09a5eed34d364bf09fe3a2a9c96751fde03a4e0cfa51a04d784c
homepage    : http://projects.gnome.org/gconf/
license     :
    - LGPL-2.0
summary     : GNOME Configuration Database
description : |
    The GConf package contains a configuration database system used by many GNOME applications.
component   : desktop.gnome.core
builddeps   :
    - pkgconfig32(gio-2.0)
    - pkgconfig32(dbus-1)
    - pkgconfig32(dbus-glib-1)
    - pkgconfig32(libxml-2.0)
    - libgcrypt-32bit-devel
emul32     : yes
setup      : |
    EM32EX=""
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        EM32EX="--disable-defaults-service"
    fi
    %configure --prefix=/usr \
               --disable-static \
               --disable-orbit \
               --libexecdir=%libdir%/GConf \
               $EM32EX
build      : |
    %make
install    : |
    %make_install
    # Set up the default pointer
    if [[ -z "${EMUL32BUILD}" ]]; then
        ln -sv gconf.xml.defaults $installdir/etc/gconf/gconf.xml.system
    fi
